/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;




import Presentacion.MDIPrincipal;
import estadistica.modelo.Clase;
import estadistica.modelo.Frecuencia;
import estadistica.recursos.JPColor;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Enumeration;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jonathan
 */
public class JIFCuantitativo extends javax.swing.JInternalFrame {

  
   	private static final long serialVersionUID = 1L;
	private Frecuencia frec;
   
        MDIPrincipal frame;
   private DefaultTableModel modeloLista;
   
   private int idus=MDIPrincipal.getvSeccion();
    public JIFCuantitativo() throws SQLException {
        initComponents();
        
        frec = new Frecuencia();
        
        txt_ingresar.setColumns(25);
        txt_ingresar.setText("63,43,64,59,50,82,51,72,60,64,36,70,52,67,76,49,57,51,57,44,56,62,62,67,73,64,43,60,61,56,59,68,71,67,62,35,62,61,51,63,78,26,55,81,60");

        
        
            Color c1=new Color(66,111,166);
            Color c2=new Color(102,174,118);
            JPColor miColor=new JPColor(c1,c2);
            miColor.setSize(this.getSize());
            panel_enc.add(miColor);
            
            
            tb_frecuencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "[ Rango", "fi", "Fi", "hi", "Hi", "hi%", "Hi%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
       
            
        
            
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_enc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ingresar = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        btn_calcular = new javax.swing.JButton();
        panel_linea = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb_frecuencia = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        btn_graficar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tabla de frecuencias Variables Cuantitativas -- JA");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estadistica/recursos/icono_analytics.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 0));
        jLabel34.setText("Variables Cuantitativas");

        javax.swing.GroupLayout panel_encLayout = new javax.swing.GroupLayout(panel_enc);
        panel_enc.setLayout(panel_encLayout);
        panel_encLayout.setHorizontalGroup(
            panel_encLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_encLayout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(301, 301, 301))
        );
        panel_encLayout.setVerticalGroup(
            panel_encLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_encLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_encLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_encLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel34)
                        .addContainerGap(23, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso de Datos"));

        jLabel1.setText("Datos separador por comas:");

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_calcular.setText("Calcular");
        btn_calcular.setEnabled(false);
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ingresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ingresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_calcular)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ingresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btn_calcular))
        );

        panel_linea.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de frecuencias"));

        tb_frecuencia.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        tb_frecuencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tb_frecuencia);

        javax.swing.GroupLayout panel_lineaLayout = new javax.swing.GroupLayout(panel_linea);
        panel_linea.setLayout(panel_lineaLayout);
        panel_lineaLayout.setHorizontalGroup(
            panel_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );
        panel_lineaLayout.setVerticalGroup(
            panel_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        btn_graficar.setText("Graficar");
        btn_graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_graficar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_graficar)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_enc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_linea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_enc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        String[] str = txt_ingresar.getText().trim().split(",");
        float[] datos = new float[str.length];
        txt_area.append("Datos:  ");
        for (int i = 0; i < datos.length; i++) {
            datos[i] = Float.parseFloat(str[i]);
            txt_area.append(str[i] + " ");
        }
        frec.setValor(datos);
        txt_ingresar.setText("");
        btn_calcular.setEnabled(true);
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        Clase[] clases = frec.getClases();
        DefaultTableModel modelo = (DefaultTableModel) tb_frecuencia.getModel();

        int n = frec.getK();
        int[] abs = frec.getFrecAbs();
        int[] absAc = frec.getFrecAbsAc();
        float[] rel = frec.getFrecRel();
        float[] relAc = frec.getFrecRelAc();
        txt_area.append("\n n-Cantidad de valores = " + frec.getValor().length);
        txt_area.append("\nRango = " + frec.getRango());
        txt_area.append("\nK = " + frec.getK());
        txt_area.append("\nA = " + frec.getA());
        txt_area.append("\n<-----Indicadores de Tendencia Central----->");
        txt_area.append("\nMedia = " + frec.media());
        txt_area.append("\nMediana = " + frec.mediana());
        txt_area.append("\nModa = " + frec.moda());
        txt_area.append("\n<-----Indicadores de Variabilidad----->");
        txt_area.append("\nMinimo = " + frec.getMin());
        txt_area.append("\nMaximo = " + frec.getMax());
        txt_area.append("\nRango = " + frec.getRango());
        txt_area.append("\nVarianza (S2) = " + frec.varianza());
        txt_area.append("\nDesviación Estandar (S) = " + frec.desviacion_estandar());
        txt_area.append("\nCoeficiente de Variación (CV) = " + frec.coeficiente());


        borrarFilas();
        for (int i = 0; i < n; i++) {
            // Primero colocamos las marcas de clase
            String str = "[ " + Math.round(clases[i].getLimInf()) + "-" + Math.round(clases[i].getLimSup()) + " ]";
            modelo.addRow(new String[]{str, abs[i] + "", absAc[i] + ""});
            modelo.setValueAt(redondear(rel[i], 4), i, 3);
            modelo.setValueAt(redondear(relAc[i], 4), i, 4);
            modelo.setValueAt(redondear(rel[i], 4)*100, i, 5);
            modelo.setValueAt(redondear(relAc[i], 4)*100, i, 6);
        }
        
           setCellRender(tb_frecuencia);
        btn_graficar.setEnabled(true);
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficarActionPerformed
        dlgGraf graf=new dlgGraf(frec, frame, true);
        graf.setLocationRelativeTo(this);
        graf.setVisible(true);
    }//GEN-LAST:event_btn_graficarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_graficar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel panel_enc;
    private javax.swing.JPanel panel_linea;
    private javax.swing.JTable tb_frecuencia;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_ingresar;
    // End of variables declaration//GEN-END:variables

  
   private void borrarFilas() {
        DefaultTableModel modelo = (DefaultTableModel) tb_frecuencia.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(0);
        }
    }
   
    private float redondear(float d, int i) {
        float valor = 0;
        int factor=10*(i+1);
        valor = d;
        valor = valor * factor;
        valor = java.lang.Math.round(valor);
        valor = valor / factor;

        return valor;
    }
   
     
       public void setCellRender(JTable table) {
            Enumeration<TableColumn> en = table.getColumnModel().getColumns();
                    while (en.hasMoreElements()) {
                        TableColumn tc = en.nextElement();
                        tc.setCellRenderer(new CellRenderer());
        }
    }
       


}
