/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;





import estadistica.conexion.ConexionBD;
import estadistica.daos.DaoCualitativa;
import estadistica.daos.Dao_Cualitativa_Det;
import estadistica.modelo.Cualitativa;
import estadistica.modelo.Cualitativa_det;
import estadistica.recursos.JPColor;
import estadistica.reporte.Reporte;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jonathan
 */
public class JIFCualitativo extends javax.swing.JInternalFrame {

  
   
   private DefaultTableModel modeloLista;
   private ConexionBD con;
   private Cualitativa c;
   private Cualitativa_det d;
   private DaoCualitativa daoc;
   private Dao_Cualitativa_Det daod;
   private int id_e;
   
   private DefaultTableModel modelo;
   
   private Reporte reporte;

   
   private int idus=MDIPrincipal.getvSeccion();
   DecimalFormat formateador = new DecimalFormat("####.##");
    public JIFCualitativo() throws SQLException {
        initComponents();
       
            Color c1=new Color(66,111,166);
            Color c2=new Color(102,174,118);
            JPColor miColor=new JPColor(c1,c2);
            miColor.setSize(this.getSize());
            panel_enc.add(miColor);
            
          c=new Cualitativa();
        
           c.setFecha(new Date());
        
           daoc=new DaoCualitativa();
        
      
           daoc.guardar(c);
           
            id_e=DaoCualitativa.getId();

            
            
               modelo=new DefaultTableModel();

               
               modelo.addColumn("Variable");
               modelo.addColumn("Frecuencia Absoluta (n)");
               modelo.addColumn("Frecuencia relativa (%)");
       
            
        
            
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_enc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_variable = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        btn_calcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_valor = new javax.swing.JTextField();
        btn_graficas = new javax.swing.JButton();
        panel_linea = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb_frecuencia = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tabla de frecuencias Variables Cualitativas-- JA");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estadistica/recursos/icono_analytics.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 0));
        jLabel34.setText("Variables Cualitativas");

        javax.swing.GroupLayout panel_encLayout = new javax.swing.GroupLayout(panel_enc);
        panel_enc.setLayout(panel_encLayout);
        panel_encLayout.setHorizontalGroup(
            panel_encLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_encLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(301, 301, 301))
        );
        panel_encLayout.setVerticalGroup(
            panel_encLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_encLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_encLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_encLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel34)
                        .addContainerGap(23, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso de Datos"));

        jLabel1.setText("Variable Cualitativa");

        txt_variable.setText("variable");

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_calcular.setText("Calcular");
        btn_calcular.setEnabled(false);
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor");

        txt_valor.setText("0");

        btn_graficas.setText("Graficas");
        btn_graficas.setEnabled(false);
        btn_graficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_variable, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ingresar)
                .addGap(18, 18, 18)
                .addComponent(btn_calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_graficas)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_variable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ingresar)
                    .addComponent(jLabel2)
                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcular)
                    .addComponent(btn_graficas))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        panel_linea.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de frecuencias"));

        tb_frecuencia.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        tb_frecuencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tb_frecuencia);

        javax.swing.GroupLayout panel_lineaLayout = new javax.swing.GroupLayout(panel_linea);
        panel_linea.setLayout(panel_lineaLayout);
        panel_lineaLayout.setHorizontalGroup(
            panel_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );
        panel_lineaLayout.setVerticalGroup(
            panel_lineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_enc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_linea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_enc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        
  
       
           daod=new Dao_Cualitativa_Det();
        
           d=new Cualitativa_det();
           
           d.setId_c(id_e);
           d.setVariable(txt_variable.getText());
           d.setFrec_abs(Integer.parseInt(txt_valor.getText()));
           
           daod.guardar(d);
           
           btn_calcular.setEnabled(true);
           btn_graficas.setEnabled(true);
           
           txt_valor.setText("0");
           txt_variable.setText("variable Cualitativa.");
           
         
        
        
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
      try {
        
        
       con=new ConexionBD();
       double total=0;
       int id=0;
       int frecuencia_abs=0;
       double frecuencia_relat;
       
       ResultSet objtotal=con.executeQuery("SELECT sum(frecuencia_abs) as total FROM detalle where id_en="+id_e+"");

       
       if(objtotal.next())
           
       {
           total=objtotal.getInt("total");
       }
       
       ResultSet obj=con.executeQuery("SELECT id, frecuencia_abs FROM detalle where id_en="+id_e+"");
       
           while (obj.next())
           {
               frecuencia_abs=obj.getInt("frecuencia_abs");
               id=obj.getInt("id");
               
               System.out.println(frecuencia_abs);
               System.out.println(total);
               
               frecuencia_relat=(frecuencia_abs/total)*100;
               
               formateador.format(frecuencia_relat);
                System.out.println(frecuencia_relat);

               
               con.executeUpdateQuery("UPDATE detalle SET frecuencia_relat="+frecuencia_relat+" WHERE id="+id+"");
           }
           LimpiarTabla();
           detalleTabla();
           con.desconectar();
       } catch (Exception ex) {
           Logger.getLogger(JIFCualitativo.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_graficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficasActionPerformed
        reporte=new Reporte();
        
        reporte.ejecutarReporte(id_e);
    }//GEN-LAST:event_btn_graficasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_graficas;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel panel_enc;
    private javax.swing.JPanel panel_linea;
    private javax.swing.JTable tb_frecuencia;
    private javax.swing.JTextField txt_valor;
    private javax.swing.JTextField txt_variable;
    // End of variables declaration//GEN-END:variables

  
   
    
     public void detalleTabla()
   {
       try
        {
         con=new ConexionBD();
            
        ResultSet obj=con.executeQuery("SELECT variable,frecuencia_abs,frecuencia_relat FROM detalle  WHERE id_en="+id_e+" ORDER BY id ASC ");
            
         while (obj.next()) 
        {
        
        Object [] datos = new Object[3];
        
     
        for (int i=0;i<3;i++)
        {
            datos[i] =obj.getObject(i+1);
        }

         modelo.addRow(datos);
       
        }
         
           
           tb_frecuencia.setModel(modelo);
           
   
      
           
           
           setCellRender(tb_frecuencia);
           con.desconectar();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
   }
  
    
       public void LimpiarTabla()
    {
  
        for(int i=modelo.getRowCount()-1;i>=0;i--)
        {
            modelo.removeRow(i);
            
        }
    }
  
    
   
     
       public void setCellRender(JTable table) {
            Enumeration<TableColumn> en = table.getColumnModel().getColumns();
                    while (en.hasMoreElements()) {
                        TableColumn tc = en.nextElement();
                        tc.setCellRenderer(new CellRenderer());
        }
    }
       
       
       
       
       
       
       
       
      
       
        


}
